### ISSUE TITLE
WHO_IS.js

### ISSUE THREAD

**Issue by uarloque** [typofx/plata#21]
P4 S4 LOW LOW

/painel/insert.php

- SIMILARWEB When pasted full link, "http" not supposed to be there. Neither 'www.' 'ie.' 'br.' 'us.' before domain.
- Same bug for WHO.IS

**Comment by adriel-lab** [comment]
Hi,

Just wanted to let you know that I've checked the issue you mentioned.

**Comment by uarloque** [comment]
Tks
