### ISSUE TITLE
Listar Link

### ISSUE THREAD

**Issue by uarloque** [typofx/plata#22]
[ LOW LEVEL ]

- When any special char is added on the "Obs textbox" the BD crash.
- Similarweb doesnt reconise links after TLD (Top Level Domain), remove everything from it, please.

**Comment by adriel-lab** [comment]
Issue Resolved: [LOW LEVEL]

We've successfully resolved the reported problems:

Database Crashes with Special Characters: We've implemented measures to handle special characters in the "Obs" textbox, preventing crashes and enhancing security.

Incorrect Link Recognition by Similarweb: We've adjusted the link extraction process to ensure accurate link processing by Similarweb.
